import { Script } from "./script"
import { Scroll } from "./scroll"
import { Photoscroll } from "./photoscroll"
import { Contact } from "./contact"
import { About } from "./about"
import { Navbar } from "./navbar"
import { Certs } from "./certs"
